// lib/forensics/pdfMeta.ts
// PDF metadata and dates. Extracts Producer, Creator, CreationDate, ModDate,
// page count and produces evidence for the wrong-tool and edited-after-issuance
// signals.
//
// buildMetaEvidence() is a pure function over the pdf.js `info` object so it can
// be unit-tested in Node without a browser. readPdfMeta() is the browser entry
// point: it loads pdf.js lazily (client-only) and then calls buildMetaEvidence.

import type { DocMetadata, EvidenceItem } from "../types";

// Generative tools: a synthetic-origin trace (spoofable, so weighted honestly).
const GENERATOR_TOOLS = [
  "chatgpt",
  "openai",
  "gpt",
  "gemini",
  "dall",
  "midjourney",
  "stable diffusion",
  "canva",
  "copilot",
];

// Consumer document editors: a wrong-tool tamper trace for an issued document.
const EDITOR_TOOLS = [
  "microsoft word",
  "word",
  "microsoft",
  "ilovepdf",
  "smallpdf",
  "pdfescape",
  "libreoffice",
  "google docs",
  "figma",
  "acrobat",
  "foxit",
];

export function parsePdfDate(d?: string | null): Date | null {
  if (!d) return null;
  const m = /D:(\d{4})(\d{2})(\d{2})(\d{2})?(\d{2})?(\d{2})?/.exec(d);
  if (!m) return null;
  const [, y, mo, da, h = "00", mi = "00", s = "00"] = m;
  return new Date(Date.UTC(+y, +mo - 1, +da, +h, +mi, +s));
}

export interface PdfInfoLike {
  Producer?: string;
  Creator?: string;
  CreationDate?: string;
  ModDate?: string;
}

export function buildMetaEvidence(
  info: PdfInfoLike | undefined,
  numPages: number
): { metadata: DocMetadata; evidence: EvidenceItem[] } {
  const evidence: EvidenceItem[] = [];
  const producer = info?.Producer;
  const creator = info?.Creator;
  const created = parsePdfDate(info?.CreationDate);
  const modified = parsePdfDate(info?.ModDate);

  const hay = `${producer ?? ""} ${creator ?? ""}`.toLowerCase();
  const genHit = GENERATOR_TOOLS.find((t) => hay.includes(t));
  const edHit = !genHit ? EDITOR_TOOLS.find((t) => hay.includes(t)) : undefined;

  if (genHit) {
    evidence.push({
      id: "producer",
      signal: "producer-generator",
      severity: "critical",
      title: "Produced by a generative tool",
      detail: `The file reports producer "${
        producer ?? creator
      }". Generative tools such as ${genHit} are a synthetic-origin signal. Metadata like this is spoofable, so Attesta treats it as a supporting signal, not proof.`,
      weight: 0.6,
    });
  } else if (edHit) {
    evidence.push({
      id: "producer",
      signal: "producer-editor",
      severity: "critical",
      title: "Produced by a consumer editor",
      detail: `The file reports producer "${
        producer ?? creator
      }". A document from an institution would normally be generated by that institution's system, not by ${edHit}.`,
      weight: 0.6,
    });
  }

  if (created && modified && modified.getTime() - created.getTime() > 60_000) {
    const days = Math.round(
      (modified.getTime() - created.getTime()) / 86_400_000
    );
    evidence.push({
      id: "moddate",
      signal: "mod-after-create",
      severity: "warn",
      title: "Edited after it was created",
      detail: `Last saved ${
        days >= 1 ? days + " day(s)" : "moments"
      } after creation. Original issued documents are usually not re-saved after they are generated.`,
      weight: 0.35,
    });
  } else if (created) {
    evidence.push({
      id: "dates-consistent",
      signal: "metadata",
      severity: "info",
      title: "Dates are internally consistent",
      detail:
        "The document's creation and last-saved times match, consistent with a file generated once and not re-saved.",
      weight: 0,
    });
  }

  // Always-on info row so the evidence list feels thorough even when clean.
  evidence.push({
    id: "metadata",
    signal: "metadata",
    severity: "info",
    title: "Document metadata read",
    detail: `Producer: ${producer ?? "unknown"}. ${
      created ? "Created " + created.toISOString().slice(0, 10) : "No creation date"
    }${
      modified ? ", last modified " + modified.toISOString().slice(0, 10) : ""
    }. ${numPages} page(s).`,
    weight: 0,
  });

  const metadata: DocMetadata = {
    producer,
    creator,
    creationDate: created?.toISOString(),
    modDate: modified?.toISOString(),
    pageCount: numPages,
  };
  return { metadata, evidence };
}

export async function readPdfMeta(
  bytes: Uint8Array
): Promise<{ metadata: DocMetadata; evidence: EvidenceItem[] }> {
  const { getPdfjs } = await import("./pdfjs");
  const pdfjsLib = await getPdfjs();
  // pdf.js transfers (detaches) the ArrayBuffer it is given, which would leave
  // the caller's `bytes` empty for the incremental-update byte scan that runs
  // afterward. Hand pdf.js its own copy so the original bytes survive.
  const doc = await pdfjsLib.getDocument({ data: bytes.slice() }).promise;
  const meta = await doc.getMetadata();
  return buildMetaEvidence(meta.info as PdfInfoLike, doc.numPages);
}
